//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountId { get; set; }
        public string AccountType { get; set; }
        public int CustomerId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual LoanAccount LoanAccount { get; set; }
        public virtual SavingsAccount SavingsAccount { get; set; }
    }
}
