//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanAccount()
        {
            this.LoanTransactions = new HashSet<LoanTransaction>();
        }
    
        public int AccountId { get; set; }
        public decimal LoanAmount { get; set; }
        public System.DateTime StartDate { get; set; }
        public int TenureMonths { get; set; }
        public decimal AnnualROI { get; set; }
        public Nullable<decimal> EMI { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public Nullable<bool> IsClosed { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanTransaction> LoanTransactions { get; set; }
    }
}
